"""empty message

Revision ID: 465700f2ae8a
Revises: 3c77c1a709aa
Create Date: 2025-11-06 21:44:50.435179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465700f2ae8a'
down_revision = '3c77c1a709aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.alter_column('planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
